export const CATS = [
  { id:'fl',    emoji:'🥦', name:'Fruits & Légumes',     short:'Fruits & Lég.', color:'#EAF7EC' },
  { id:'fec',   emoji:'🍞', name:'Féculents & Céréales', short:'Féculents',     color:'#FBF1E3' },
  { id:'lait',  emoji:'🥛', name:'Produits Laitiers',    short:'Laitiers',      color:'#EAF2FB' },
  { id:'vp',    emoji:'🥩', name:'Viandes & Poissons',   short:'Viandes',       color:'#FBEBEC' },
  { id:'mg',    emoji:'🧈', name:'Matières Grasses',     short:'Mat. Grasses',  color:'#FCF6E3' },
  { id:'surg',  emoji:'🧊', name:'Surgelés',             short:'Surgelés',      color:'#E7F6FB' },
  { id:'bois',  emoji:'🥤', name:'Boissons',             short:'Boissons',      color:'#F0EBFB' },
  { id:'suc',   emoji:'🍫', name:'Produits Sucrés',      short:'Sucrés',        color:'#FBEDF4' },
  { id:'apero', emoji:'🍿', name:'Apéro',                short:'Apéro',         color:'#FCF0E5' },
  { id:'soin',  emoji:'🧴', name:'Soin & Santé',         short:'Soin',          color:'#E6F6F3' },
  { id:'men',   emoji:'🧹', name:'Produit Ménager',      short:'Ménager',       color:'#EFF7E4' },
  { id:'foyer', emoji:'🏠', name:'Foyer',                short:'Foyer',         color:'#F0F1F3' },
]

export const CATALOG = {
  fl:[
    ['Bananes',1.20],['Pommes',2.10],['Tomates',1.95],['Salade',0.99],['Oignons',1.10],
    ['Carottes',1.30],['Citrons',1.45],['Avocat',1.60],['Pommes de terre',2.50],
    ['Fraises',3.20],['Framboises',3.50],['Mangue',1.80],['Ananas',2.40],['Cerises',4.20],
    ['Brocoli',1.60],['Courgettes',1.40],['Aubergine',1.30],['Poivrons',1.90],
    ['Champignons',1.80],['Concombre',0.90],['Épinards',1.50],['Ail',0.80],
    ['Céleri',1.20],['Persil',0.70],['Basilic',0.90],['Betterave',1.10],['Radis',0.85],
    ['Poires',2.20],['Kiwis',2.60],['Pastèque',3.90],['Melon',2.80],['Raisin',3.10],
    ['Pêches',2.70],['Abricots',2.50],['Clémentines',2.30],['Pamplemousse',1.90],
    ['Poireaux',1.60],['Chou-fleur',1.90],['Chou blanc',1.50],['Chou rouge',1.60],
    ['Fenouil',1.70],['Navets',1.30],['Panais',1.60],['Patate douce',2.20],
    ['Échalotes',1.40],['Ciboulette',0.90],['Coriandre',0.85],['Thym',0.80],
    ['Romarin',0.85],['Gingembre',1.60],
  ],
  fec:[
    ['Pâtes',0.95],['Riz',1.40],['Pain de mie',1.15],['Semoule',1.20],
    ['Quinoa',2.80],['Lentilles',1.50],['Tortillas',1.90],
    ['Farine',0.85],['Flocons d\'avoine',1.60],['Riz complet',1.80],
    ['Pain complet',1.40],['Boulgour',1.70],['Maïzena',0.90],['Chapelure',1.10],
    ['Spaghetti',1.10],['Pâtes complètes',1.30],['Nouilles',1.50],['Vermicelles',1.40],
    ['Couscous',1.60],['Baguette',1.10],['Pain complet tranché',1.60],
    ['Pain de campagne',2.20],['Pain burger',2.10],['Biscottes',1.90],
    ['Crêpes',2.40],['Gaufres',2.60],
  ],
  lait:[
    ['Lait',0.89],['Yaourts',1.85],['Œufs',2.10],['Fromage râpé',8.00],
    ['Crème fraîche',4.50],['Camembert',1.70],['Mozzarella',1.30],
    ['Gruyère',11.00],['Ricotta',1.80],['Mascarpone',2.20],['Skyr',1.60],
    ['Lait d\'amande',2.50],['Lait d\'avoine',2.30],['Crème liquide',4.50],
    ['Lait demi-écrémé',0.95],['Lait entier',1.05],['Lait écrémé',0.90],
    ['Yaourts nature',1.60],['Yaourts aux fruits',2.10],['Fromage blanc',3.00],
    ['Parmesan',15.00],['Chèvre',2.80],['Feta',2.50],['Emmental',9.50],
    ['Babeurre',1.30],['Petit-suisse',1.80],
  ],
  vp:[
    ['Poulet',7.00],['Steak haché',9.00],['Jambon',2.30],['Lardons',9.00],
    ['Thon en boîte',1.60],['Saumon',20.00],['Saucisses',2.90],
    ['Dinde',10.00],['Escalope de veau',18.00],['Crevettes',14.00],
    ['Sardines',1.40],['Moules',5.00],['Tofu',2.40],['Filet de cabillaud',17.00],
    ['Cuisses de poulet',6.00],['Blanc de poulet',9.00],['Merguez',3.40],
    ['Chorizo',13.00],['Bacon',2.90],['Côtes de porc',8.00],['Rôti de bœuf',15.00],
    ['Agneau',18.00],['Thon frais',17.00],['Truite',13.00],['Colin',14.00],['Seitan',3.10],
  ],
  mg:[
    ['Beurre',8.00],["Huile d'olive",4.50],['Huile de tournesol',1.80],['Margarine',3.50],
    ['Huile de coco',12.00],['Graisse de canard',10.00],['Crème de coco',4.00],
    ['Beurre doux',8.00],['Beurre demi-sel',8.20],['Huile de colza',2.40],
    ['Huile de sésame',12.00],["Huile d'arachide",2.90],['Huile de pépins de raisin',6.00],
    ['Saindoux',6.00],['Ghee',16.00],['Crème végétale',6.50],['Mayonnaise',5.00],
    ['Vinaigrette',4.00],['Pâte à tartiner végétale',4.50],['Suif',4.00],
  ],
  surg:[
    ['Pizzas',2.50],['Glace',2.90],['Légumes surgelés',1.95],['Frites',1.70],
    ['Nuggets',5.50],['Poisson pané',3.40],['Épinards surgelés',1.60],
    ['Wok de légumes',2.80],['Edamame',6.00],['Pizza 4 fromages',3.20],
    ['Glaçons',1.20],['Sorbet',3.10],['Petits pois surgelés',1.70],
    ['Haricots verts surgelés',1.80],['Ratatouille surgelée',2.20],
    ['Crevettes surgelées',12.00],['Saumon surgelé',14.00],['Quiche surgelée',3.30],
    ['Lasagnes surgelées',3.60],['Croque-monsieur surgelé',2.80],
    ['Beignets surgelés',2.90],['Fruits rouges surgelés',8.00],
  ],
  bois:[
    ['Coca',1.50],["Jus d'orange",1.80],['Eau',0.40],['Bière',4.20],
    ['Café',9.50],['Thé',2.10],['Sirop',2.30],['Limonade',1.40],
    ['Kombucha',4.50],['Vin rouge',5.80],['Vin blanc',5.50],['Jus de pomme',1.90],
    ['Eau gazeuse',0.60],['Ice tea',1.60],['Jus multifruits',1.90],
    ['Jus de raisin',2.00],['Soda citron',1.50],['Boisson énergisante',3.00],
    ['Cidre',3.20],['Champagne',20.00],['Rosé',5.40],['Whisky',18.90],
    ['Rhum',16.50],['Lait chocolaté',1.70],
  ],
  suc:[
    ['Chocolat',16.00],['Biscuits',6.50],['Céréales',5.00],['Confiture',4.50],
    ['Bonbons',8.00],['Nutella',6.00],['Miel',9.00],['Sucre',0.90],
    ['Sucre glace',3.80],['Sirop d\'érable',18.00],['Compote',1.30],
    ['Chocolat noir',15.00],['Chocolat au lait',16.00],['Barres chocolatées',1.60],
    ['Gâteaux secs',6.00],['Madeleines',1.80],['Pâtisseries',3.20],
    ['Bonbons gélifiés',8.00],['Chewing-gum',1.20],['Sucre roux',1.80],
    ['Édulcorant',15.00],['Pâte à tartiner noisette',6.00],
  ],
  apero:[
    ['Chips',5.00],['Cacahuètes',5.00],['Olives',7.00],['Crackers',9.00],
    ['Saucisson',13.00],['Houmous',8.00],['Noix',9.00],['Pistaches',16.00],
    ['Tapenade',12.00],['Mini saucisses',2.90],['Guacamole',10.00],
    ['Chips tortillas',6.50],['Bretzels',8.00],['Amandes',11.00],
    ['Noix de cajou',13.00],['Rillettes',10.00],['Terrine',11.00],
    ['Fromage à tartiner',10.00],['Salami',13.00],['Blinis',2.20],
    ['Cornichons',6.50],['Sauce cocktail',5.50],
  ],
  soin:[
    ['Dentifrice',22.00],['Gel douche',4.50],['Shampoing',5.00],['Déodorant',2.30],
    ['Coton-tiges',1.20],['Mouchoirs',1.40],['Savon',1.60],['Rasoir',3.50],
    ['Crème hydratante',40.00],['Coton',1.80],['Tampons',3.20],['Serviettes hygiéniques',2.90],
    ['Après-shampoing',5.00],['Brosse à dents',2.50],['Bain de bouche',7.00],
    ['Fil dentaire',2.20],['Mousse à raser',11.00],['Crème solaire',35.00],
    ['Protège-slips',2.40],['Lingettes',2.10],['Pansements',2.60],
    ['Paracétamol',3.20],['Vitamines',5.40],['Préservatifs',4.90],
  ],
  men:[
    ['Liquide vaisselle',2.00],['Éponges',1.50],['Lessive',2.50],['Sacs poubelle',2.40],
    ['Nettoyant',2.50],['Sopalin',2.60],['Pastilles lave-vaisselle',5.80],
    ['Spray nettoyant',3.00],['Sacs congélation',2.20],['Plaquettes WC',3.10],
    ['Adoucissant',2.80],['Détachant',6.00],['Javel',1.20],['Anticalcaire',3.00],
    ['Nettoyant vitres',3.50],['Nettoyant sol',2.80],['Gants ménagers',1.80],
    ['Serpillière',2.90],['Balai',6.50],['Chiffons microfibre',3.40],
    ['Désodorisant',2.60],['Insecticide',9.00],
  ],
  foyer:[
    ['Piles',4.50],['Ampoules',3.20],['Bougies',2.80],['Scotch',1.60],
    ['Croquettes chat',2.50],['Papier aluminium',1.90],['Film alimentaire',1.70],
    ['Sacs de course',1.20],['Allumettes',0.90],['Croquettes chien',2.20],
    ['Papier cuisson',2.10],['Litière chat',1.20],['Pâtée chat',1.40],
    ['Pâtée chien',1.60],['Ampoules LED',4.90],['Piles rechargeables',8.90],
    ['Chargeur',12.90],['Cintres',3.20],['Housses de rangement',4.50],
    ['Bougies parfumées',5.20],['Pinces à linge',2.30],['Ficelle',1.50],
  ],
}

export const EMOJI_MAP = {
  // Fruits & Légumes
  'Bananes':'🍌','Pommes':'🍎','Tomates':'🍅','Salade':'🥬','Oignons':'🧅','Carottes':'🥕',
  'Citrons':'🍋','Avocat':'🥑','Pommes de terre':'🥔','Fraises':'🍓','Framboises':'🫐',
  'Mangue':'🥭','Ananas':'🍍','Cerises':'🍒','Brocoli':'🥦','Courgettes':'🥒',
  'Aubergine':'🍆','Poivrons':'🫑','Champignons':'🍄','Concombre':'🥒','Épinards':'🥬',
  'Ail':'🧄','Céleri':'🥬','Persil':'🌿','Basilic':'🌿','Betterave':'🫚','Radis':'🌱',
  'Poires':'🍐','Kiwis':'🥝','Pastèque':'🍉','Melon':'🍈','Raisin':'🍇','Pêches':'🍑',
  'Abricots':'🍑','Clémentines':'🍊','Pamplemousse':'🍊','Poireaux':'🥬','Chou-fleur':'🥦',
  'Chou blanc':'🥬','Chou rouge':'🥬','Fenouil':'🌿','Navets':'🥕','Panais':'🥕',
  'Patate douce':'🍠','Échalotes':'🧅','Ciboulette':'🌿','Coriandre':'🌿','Thym':'🌿',
  'Romarin':'🌿','Gingembre':'🫚',
  // Féculents
  'Pâtes':'🍝','Riz':'🍚','Pain de mie':'🍞','Semoule':'🌾','Quinoa':'🌾','Lentilles':'🫘',
  'Tortillas':'🌮','Farine':'🌾',"Flocons d'avoine":'🌾','Riz complet':'🍚',
  'Pain complet':'🍞','Boulgour':'🌾','Maïzena':'🌾','Chapelure':'🍞',
  'Spaghetti':'🍝','Pâtes complètes':'🍝','Nouilles':'🍜','Vermicelles':'🍜',
  'Couscous':'🌾','Baguette':'🥖','Pain complet tranché':'🍞','Pain de campagne':'🍞',
  'Pain burger':'🍔','Biscottes':'🍞','Crêpes':'🥞','Gaufres':'🧇',
  // Laitiers
  'Lait':'🥛','Yaourts':'🥛','Œufs':'🥚','Fromage râpé':'🧀','Crème fraîche':'🥛',
  'Camembert':'🧀','Mozzarella':'🧀','Parmesan':'🧀','Gruyère':'🧀','Ricotta':'🧀',
  'Mascarpone':'🧀','Skyr':'🥛',"Lait d'amande":'🥛',"Lait d'avoine":'🥛','Crème liquide':'🥛',
  'Lait demi-écrémé':'🥛','Lait entier':'🥛','Lait écrémé':'🥛','Yaourts nature':'🥛',
  'Yaourts aux fruits':'🍓','Fromage blanc':'🥛','Chèvre':'🧀','Feta':'🧀',
  'Emmental':'🧀','Babeurre':'🥛','Petit-suisse':'🥛',
  // Viandes & Poissons
  'Poulet':'🍗','Steak haché':'🥩','Jambon':'🍖','Lardons':'🥓','Thon en boîte':'🐟',
  'Thon':'🐟','Saumon':'🐟','Saucisses':'🌭','Dinde':'🍗','Escalope de veau':'🥩',
  'Crevettes':'🦐','Sardines':'🐟','Moules':'🐚','Tofu':'🫘','Filet de cabillaud':'🐟',
  'Cuisses de poulet':'🍗','Blanc de poulet':'🍗','Merguez':'🌭','Chorizo':'🌭',
  'Bacon':'🥓','Côtes de porc':'🥩','Rôti de bœuf':'🥩','Agneau':'🍖','Thon frais':'🐟',
  'Truite':'🐟','Colin':'🐟','Seitan':'🫘',
  // Matières Grasses
  'Beurre':'🧈',"Huile d'olive":'🫒','Huile de tournesol':'🛢️','Margarine':'🧈',
  'Huile de coco':'🥥','Graisse de canard':'🦆','Crème de coco':'🥥',
  'Beurre doux':'🧈','Beurre demi-sel':'🧈','Huile de colza':'🛢️','Huile de sésame':'🛢️',
  "Huile d'arachide":'🛢️','Huile de pépins de raisin':'🛢️','Saindoux':'🥓','Ghee':'🧈',
  'Crème végétale':'🥥','Mayonnaise':'🥫','Vinaigrette':'🥫','Pâte à tartiner végétale':'🧈',
  'Suif':'🧈',
  // Surgelés
  'Pizzas':'🍕','Glace':'🍦','Légumes surgelés':'🥦','Frites':'🍟','Nuggets':'🍗',
  'Poisson pané':'🐟','Épinards surgelés':'🥬','Wok de légumes':'🥦',
  'Edamame':'🫛','Pizza 4 fromages':'🍕',
  'Glaçons':'🧊','Sorbet':'🍧','Petits pois surgelés':'🟢','Haricots verts surgelés':'🫛',
  'Ratatouille surgelée':'🍆','Crevettes surgelées':'🦐','Saumon surgelé':'🐟',
  'Quiche surgelée':'🥧','Lasagnes surgelées':'🍝','Croque-monsieur surgelé':'🥪',
  'Beignets surgelés':'🍩','Fruits rouges surgelés':'🍓',
  // Boissons
  'Coca':'🥤',"Jus d'orange":'🧃','Eau':'💧','Bière':'🍺','Café':'☕','Thé':'🍵',
  'Sirop':'🧃','Lait de coco':'🥥','Limonade':'🍋','Kombucha':'🍶',
  'Vin rouge':'🍷','Vin blanc':'🥂','Jus de pomme':'🧃',
  'Eau gazeuse':'💧','Ice tea':'🧃','Jus multifruits':'🧃','Jus de raisin':'🧃',
  'Soda citron':'🥤','Boisson énergisante':'🥤','Cidre':'🍾','Champagne':'🍾',
  'Rosé':'🍷','Whisky':'🥃','Rhum':'🥃','Lait chocolaté':'🍫',
  // Sucrés
  'Chocolat':'🍫','Biscuits':'🍪','Céréales':'🥣','Confiture':'🍓','Bonbons':'🍬',
  'Nutella':'🍫','Miel':'🍯','Sucre':'🍚','Sucre glace':'🍚',"Sirop d'érable":'🍁',
  'Compote':'🍎',
  'Chocolat noir':'🍫','Chocolat au lait':'🍫','Barres chocolatées':'🍫',
  'Gâteaux secs':'🍪','Madeleines':'🧁','Pâtisseries':'🍰','Bonbons gélifiés':'🍬',
  'Chewing-gum':'🍬','Sucre roux':'🍚','Édulcorant':'🍬','Pâte à tartiner noisette':'🍫',
  // Apéro
  'Chips':'🥔','Cacahuètes':'🥜','Olives':'🫒','Crackers':'🍘','Saucisson':'🥓',
  'Houmous':'🥣','Noix':'🪨','Pistaches':'🟢','Tapenade':'🫒',
  'Mini saucisses':'🌭','Guacamole':'🥑',
  'Chips tortillas':'🌽','Bretzels':'🥨','Amandes':'🌰','Noix de cajou':'🌰',
  'Rillettes':'🥫','Terrine':'🥫','Fromage à tartiner':'🧀','Salami':'🥓',
  'Blinis':'🥞','Cornichons':'🥒','Sauce cocktail':'🥫',
  // Soin
  'Dentifrice':'🪥','Gel douche':'🧴','Shampoing':'🧴','Déodorant':'🧴',
  'Coton-tiges':'🧶','Mouchoirs':'🤧','Savon':'🧼','Rasoir':'🪒',
  'Crème hydratante':'🧴','Coton':'🤍','Tampons':'🌸','Serviettes hygiéniques':'🌸',
  'Après-shampoing':'🧴','Brosse à dents':'🪥','Bain de bouche':'🧴','Fil dentaire':'🧵',
  'Mousse à raser':'🧴','Crème solaire':'🧴','Protège-slips':'🌸','Lingettes':'🧻',
  'Pansements':'🩹','Paracétamol':'💊','Vitamines':'💊','Préservatifs':'📦',
  // Ménager
  'Liquide vaisselle':'🧴','Éponges':'🧽','Lessive':'🧺','Sacs poubelle':'🗑️',
  'Nettoyant':'🧴','Sopalin':'🧻','Pastilles lave-vaisselle':'✨',
  'Spray nettoyant':'🧴','Sacs congélation':'🧊','Plaquettes WC':'🚽',
  'Adoucissant':'🧺','Détachant':'🧴','Javel':'🧴','Anticalcaire':'🧴',
  'Nettoyant vitres':'🧴','Nettoyant sol':'🧴','Gants ménagers':'🧤','Serpillière':'🧹',
  'Balai':'🧹','Chiffons microfibre':'🧽','Désodorisant':'🌸','Insecticide':'🐜',
  // Foyer
  'Piles':'🔋','Ampoules':'💡','Bougies':'🕯️','Scotch':'📏','Croquettes chat':'🐱',
  'Papier aluminium':'🔘','Film alimentaire':'🔘','Sacs de course':'🛍️',
  'Allumettes':'🔥','Croquettes chien':'🐶',
  'Papier cuisson':'📄','Litière chat':'🐱','Pâtée chat':'🐱','Pâtée chien':'🐶',
  'Ampoules LED':'💡','Piles rechargeables':'🔋','Chargeur':'🔌','Cintres':'👔',
  'Housses de rangement':'🗄️','Bougies parfumées':'🕯️','Pinces à linge':'📎','Ficelle':'🧵',
  // Divers (recettes seed)
  'Curry':'🍛','Pois chiches':'🫘','Sauce':'🥫','Cheddar':'🧀','Pesto':'🌿','Maïs':'🌽',
  'Sauce tomate':'🍅',
}

export const INITIAL_ARTICLES = [
  { id:1,  name:'Pâtes',             cat:'fec',  price:0.95, qty:2, place:'liste', listId:'coloc' },
  { id:2,  name:'Bananes',           cat:'fl',   price:1.20, qty:1, place:'liste', listId:'coloc' },
  { id:3,  name:'Lait',              cat:'lait', price:0.89, qty:2, place:'liste', listId:'coloc' },
  { id:4,  name:'Œufs',              cat:'lait', price:2.10, qty:1, place:'liste', listId:'coloc' },
  { id:5,  name:'Poulet',            cat:'vp',   price:5.40, qty:1, place:'liste', listId:'coloc' },
  { id:6,  name:'Coca',              cat:'bois', price:1.50, qty:1, place:'liste', listId:'coloc' },
  { id:7,  name:'Chips',             cat:'apero',price:1.80, qty:1, place:'liste', listId:'coloc' },
  { id:8,  name:'Chocolat',          cat:'suc',  price:1.65, qty:1, place:'liste', listId:'coloc' },
  { id:9,  name:'Liquide vaisselle', cat:'men',  price:1.30, qty:1, place:'liste', listId:'coloc' },
  { id:10, name:'Beurre',            cat:'mg',   price:1.95, qty:1, place:'frigo', listId:'coloc' },
  { id:11, name:'Yaourts',           cat:'lait', price:1.85, qty:1, place:'frigo', listId:'coloc' },
  { id:12, name:'Salade',            cat:'fl',   price:0.99, qty:1, place:'frigo', listId:'coloc' },
  { id:13, name:'Café',              cat:'bois', price:3.50, qty:1, place:'liste', listId:'perso' },
  { id:14, name:'Dentifrice',        cat:'soin', price:2.20, qty:1, place:'liste', listId:'perso' },
  { id:15, name:'Bananes',           cat:'fl',   price:1.20, qty:1, place:'liste', listId:'perso' },
  { id:16, name:'Riz',               cat:'fec',  price:1.40, qty:1, place:'liste', listId:'famille' },
  { id:17, name:'Poulet',            cat:'vp',   price:5.40, qty:2, place:'liste', listId:'famille' },
  { id:18, name:'Yaourts',           cat:'lait', price:1.85, qty:2, place:'liste', listId:'famille' },
  { id:19, name:'Sopalin',           cat:'men',  price:2.60, qty:1, place:'liste', listId:'famille' },
]

export const INITIAL_RECIPES = [
  { id:'r1', emoji:'🍝', name:'Pâtes carbo',     ing:[{name:'Pâtes',cat:'fec'},{name:'Lardons',cat:'vp'},{name:'Crème fraîche',cat:'lait'},{name:'Œufs',cat:'lait'},{name:'Parmesan',cat:'lait'}] },
  { id:'r3', emoji:'🍳', name:'Omelette express', ing:[{name:'Œufs',cat:'lait'},{name:'Beurre',cat:'mg'},{name:'Fromage râpé',cat:'lait'}] },
]

export const INITIAL_LISTS = [
  { id:'perso',   emoji:'🙂', name:'Perso',   members:['Toi'],                        store:'Lidl',       city:'Lyon 7ᵉ' },
  { id:'coloc',   emoji:'🏠', name:'Coloc',   members:['Toi','Léa','Tom'],            store:'Carrefour',  city:'Villeurbanne' },
  { id:'famille', emoji:'👪', name:'Famille', members:['Toi','Maman','Papa','Lucie'], store:'Leclerc',    city:'Bron' },
]

export const INITIAL_EXPENSES = [
  { id:90, reason:'Courses Lidl',       emoji:'🛒', amount:42.30, dateLabel:'22 juin' },
  { id:91, reason:'Boulangerie',        emoji:'🥐', amount:6.80,  dateLabel:'21 juin' },
  { id:92, reason:'Marché du dimanche', emoji:'🥦', amount:18.50, dateLabel:'19 juin' },
  { id:93, reason:'Pharmacie',          emoji:'💊', amount:12.90, dateLabel:'17 juin' },
  { id:94, reason:'Carrefour',          emoji:'🛒', amount:61.40, dateLabel:'14 juin' },
]
